name: Build APK

# Cuándo se ejecuta el workflow
on:
  push:
    branches: [ main ]  # Se ejecuta al hacer push a main
  workflow_dispatch:    # Permite ejecutarlo manualmente desde la interfaz de GitHub

jobs:
  build:
    runs-on: ubuntu-latest  # Máquina virtual Linux

    steps:
      # 1. Descarga el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configura JDK para compilar Android
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'  # Distribución de Java
          java-version: '11'    # Versión compatible con Android
          cache: 'gradle'       # Cachea dependencias de Gradle para acelerar builds

      # 3. Da permisos de ejecución al wrapper de Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Construye el APK (variante debug por ahora)
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 5. Sube el APK como artefacto
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk